name: MPPCAImportanceSampling
channels:
  - conda-forge
  - defaults
  - pytorch
dependencies:
  - python=3.10
  - matplotlib
  - numpy<2.0.0
  - pip
  - pytorch
  - scikit-learn
  - tabulate
  - tqdm
  - pip:
    - jax==0.4.25
    - jaxlib==0.4.25
    - prdc
    - jax_f16==0.0.1
